apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: example-httproute
spec:
    parentRefs:
    - name: example-gateway #reference to gateway.yaml
    rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - name: {{ .Release.Name }}-rest-controller #point at service metadata.name
              port: 8080 #point at service port
          filters:
            - type: URLRewrite 
              urlRewrite:
                path:
                    type: ReplaceFullPath
                    replaceFullPath: /gg